<#macro select_national selectedVal="">
<select class="form-control select2me" name="national">
	<option <#if  selectedVal=="汉族" >selected="true"</#if> value="汉族">汉族</option>
	<option <#if  selectedVal=="蒙古族" >selected="true"</#if> value="蒙古族">蒙古族</option>
	<option <#if  selectedVal=="彝族" >selected="true"</#if> value="彝族">彝族</option>
	<option <#if  selectedVal=="侗族" >selected="true"</#if> value="侗族">侗族</option>
	<option <#if  selectedVal=="哈萨克族" >selected="true"</#if> value="哈萨克族">哈萨克族</option>
	<option <#if  selectedVal=="畲族" >selected="true"</#if> value="畲族">畲族</option>
	<option <#if  selectedVal=="纳西族" >selected="true"</#if> value="纳西族">纳西族</option>
	<option <#if  selectedVal=="仫佬族" >selected="true"</#if> value="仫佬族">仫佬族</option>
	<option <#if  selectedVal=="仡佬族" >selected="true"</#if> value="仡佬族">仡佬族</option>
	<option <#if  selectedVal=="怒族" >selected="true"</#if> value="怒族">怒族</option>
	<option <#if  selectedVal=="保安族" >selected="true"</#if> value="保安族">保安族</option>
	<option <#if  selectedVal=="鄂伦春族" >selected="true"</#if> value="鄂伦春族">鄂伦春族</option>
	<option <#if  selectedVal=="回族" >selected="true"</#if> value="回族">回族</option>
	<option <#if  selectedVal=="壮族" >selected="true"</#if> value="壮族">壮族</option>
	<option <#if  selectedVal=="瑶族" >selected="true"</#if> value="瑶族">瑶族</option>
	<option <#if  selectedVal=="傣族" >selected="true"</#if> value="傣族">傣族</option>
	<option <#if  selectedVal=="高山族" >selected="true"</#if> value="高山族">高山族</option>
	<option <#if  selectedVal=="景颇族" >selected="true"</#if> value="景颇族">景颇族</option>
	<option <#if  selectedVal=="羌族" >selected="true"</#if> value="羌族">羌族</option>
	<option <#if  selectedVal=="锡伯族" >selected="true"</#if> value="锡伯族">锡伯族</option>
	<option <#if  selectedVal=="乌孜别克族" >selected="true"</#if> value="乌孜别克族">乌孜别克族</option>
	<option <#if  selectedVal=="裕固族" >selected="true"</#if> value="裕固族">裕固族</option>
	<option <#if  selectedVal=="赫哲族" >selected="true"</#if> value="赫哲族">赫哲族</option>
	<option <#if  selectedVal=="藏族" >selected="true"</#if> value="藏族">藏族</option>
	<option <#if  selectedVal=="布依族" >selected="true"</#if> value="布依族">布依族</option>
	<option <#if  selectedVal=="白族" >selected="true"</#if> value="白族">白族</option>
	<option <#if  selectedVal=="黎族" >selected="true"</#if> value="黎族">黎族</option>
	<option <#if  selectedVal=="拉祜族" >selected="true"</#if> value="拉祜族">拉祜族</option>
	<option <#if  selectedVal=="柯尔克孜族" >selected="true"</#if> value="柯尔克孜族">柯尔克孜族</option>
	<option <#if  selectedVal=="布朗族" >selected="true"</#if> value="布朗族">布朗族</option>
	<option <#if  selectedVal=="阿昌族" >selected="true"</#if> value="阿昌族">阿昌族</option>
	<option <#if  selectedVal=="俄罗斯族" >selected="true"</#if> value="俄罗斯族">俄罗斯族</option>
	<option <#if  selectedVal=="京族" >selected="true"</#if> value="京族">京族</option>
	<option <#if  selectedVal=="门巴族" >selected="true"</#if> value="门巴族">门巴族</option>
	<option <#if  selectedVal=="维吾尔族" >selected="true"</#if> value="维吾尔族">维吾尔族</option>
	<option <#if  selectedVal=="朝鲜族" >selected="true"</#if> value="朝鲜族">朝鲜族</option>
	<option <#if  selectedVal=="土家族" >selected="true"</#if> value="土家族">土家族</option>
	<option <#if  selectedVal=="傈僳族" >selected="true"</#if> value="傈僳族">傈僳族</option>
	<option <#if  selectedVal=="水族" >selected="true"</#if> value="水族">水族</option>
	<option <#if  selectedVal=="土族" >selected="true"</#if> value="土族">土族</option>
	<option <#if  selectedVal=="撒拉族" >selected="true"</#if> value="撒拉族">撒拉族</option>
	<option <#if  selectedVal=="普米族" >selected="true"</#if> value="普米族">普米族</option>
	<option <#if  selectedVal=="鄂温克族" >selected="true"</#if> value="鄂温克族">鄂温克族</option>
	<option <#if  selectedVal=="塔塔尔族" >selected="true"</#if> value="塔塔尔族">塔塔尔族</option>
	<option <#if  selectedVal=="珞巴族" >selected="true"</#if> value="珞巴族">珞巴族</option>
	<option <#if  selectedVal=="苗族" >selected="true"</#if> value="苗族">苗族</option>
	<option <#if  selectedVal=="满族" >selected="true"</#if> value="满族">满族</option>
	<option <#if  selectedVal=="哈尼族" >selected="true"</#if> value="哈尼族">哈尼族</option>
	<option <#if  selectedVal=="佤族" >selected="true"</#if> value="佤族">佤族</option>
	<option <#if  selectedVal=="东乡族" >selected="true"</#if> value="东乡族">东乡族</option>
	<option <#if  selectedVal=="达斡尔族" >selected="true"</#if> value="达斡尔族">达斡尔族</option>
	<option <#if  selectedVal=="毛南族" >selected="true"</#if> value="毛南族">毛南族</option>
	<option <#if  selectedVal=="塔吉克族" >selected="true"</#if> value="塔吉克族">塔吉克族</option>
	<option <#if  selectedVal=="德昂族" >selected="true"</#if> value="德昂族">德昂族</option>
	<option <#if  selectedVal=="独龙族" >selected="true"</#if> value="独龙族">独龙族</option>
	<option <#if  selectedVal=="基诺族" >selected="true"</#if> value="基诺族">基诺族</option>
</select>
</#macro>